name: Deploy theme to XServer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTPS deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload theme via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /xn--y8jl1nv45j4gc69v8pl.com/public_html/wp-content/themes/sakura/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
